quic-interop/quic-interop-runner

- implementations.py
add mvfst image. 
the tests are still failing on my setup but I see server and client getting started correctly with the right arguments.
> add mvfst image

- implementations.py
Adding quiche image to the mix.
Docker image: https://github.com/junhochoi/quiche-qns
Docker Hub: https://cloud.docker.com/repository/registry-1.docker.io/junhochoi/quiche-qns
> Add quiche image

- README.md
- testcases.py
- trace.py
Depends on https://github.com/marten-seemann/quic-network-simulator/pull/58.
> add a version negotiation test case

- LICENSE.md
Fixes #6.
@janaiyengar, @lnicco, @junhochoi Are you ok with this license? Are you ok with this license? Please indicate so by commenting on / approving this PR.
> add a license

- implementations.py
This image is now built automatically when changes are merged into
quiche.
/cc @junhochoi
> Update name of quiche's Docker image

- testcases.py
> close pyshark.FileCaptures in version negotiation test

- interop.py
> set a test timeout of 60 seconds

- interop.py
- run.py
- testcases.py
- trace.py
- web/index.html
- web/script.js
- web/styles.css
> add a goodput test

- interop.py
- testcases.py
- web/styles.css
> average over 5 goodput measurements

- implementations.py
I believe it should work, but a check-in test might be useful.
> Adding picoquic

- interop.py
- web/script.js
- web/styles.css
> link to the test result from the web interface

- testcases.py
This will likely lead to some failures in the interop matrix. As far as I can see, some implementations might not multiplex transfers (according to the description of the `transfer` test, you have to use multiplexing).
This will become especially important for #42.
> verify the number of QUIC handshakes

- docker-compose.yml
- interop.py
- pull.py
- testcases.py
The iperf endpoint is here: https://github.com/marten-seemann/quic-interop-iperf-endpoint/.
> add a measurement that runs TCP cross traffic

- trace.py
> filter out ICMP packets when processing pcaps

- web/styles.css
It's already running as a test on https://interop.seemann.io.
> increase the width of the tables in the web interface

- testcases.py
- trace.py
> fix parsing of coalesced packets from a pcap

- README.md
- docker-compose.yml
> set the QLOGDIR environment variable

- interop.py
> Make client compliant msg log level match server compliant msg log level

- run.py
Specifying test cases and measurements separately has led to a lot of confusion. It's easier to use `-t` for both of them.
> remove the -m command line parameter

- README.md
- testcases.py
- trace.py
> add a 0-RTT test case

- implementations.py
Just as client for now.
Still having issues. I'm hoping somebody can take a look and
offer some guidance.
> Add Neqo to implementations list (help wanted)

- testcases.py
> add a check that 0-RTT data was sent in the 0-RTT test

- testcases.py
> add a long-RTT test case

- implementations.py
Adds MsQuic server to the mix.
> On Board Initial MsQuic Server

- web/styles.css
* reduce the font size
* reduce padding
* allow line breaks in a cell
> avoid overflowing of the web interface

- implementations.py
> Update MsQuic to Point to Official Location

- implementations.py
Currently only http3 test but more soon.
> Indicate neqo now supports server

- web/index.html
- web/script.js
> Give more info about end time and estimated next end time

- implementations.py
The sources for the image are available at https://github.com/nginx/nginx-quic-qns/
> Updated nginx to official location

- run.py
> add a command line flag for the log directory

- cron.py
- docker-compose.yml
@larseggert will use this disable colored logging on the server.
> pass a CRON environment variable to client and server containers

- run.py
> show all available testcase in help message

- run.py
small cli improvements that make life easier
> Improve cli

- trace.py
> don't show pyshark errors except when debug logging

- testcases.py
Extracted @larseggert's fix out of #163.
> fix passing of key log files to pyshark

- web/Caddyfile
> set CORS headers such that other sites can access the JSON

- testcases.py
For some reason I couldn't push to #163 (GitHub was giving me an OAuth error, no idea why). So this PR will close #163.
> add an ECN test case

- .github/workflows/deploy.yml
I'm tired of running `git pull` on my server every time we make a change to the website.
> deploy web/ to the interop server when pushing to master

- web/cleanup.sh
This script is intended to be run by a cron job on the interop.seemann.io server.
> add a script to delete old log directories

- interop.py
- testcases.py
- web/index.html
- web/script.js
- web/styles.css
Fixes #178.
I used the testcase descriptions from the Google Sheet where suitable. There are a few missing ones left as `TODO`.
> Testcase descriptions

- .github/workflows/aggregate.py
- interop.py
- web/script.js
> fix the aggregation script to include test descriptions and version infos

- web/index.html
- web/script.js
- web/styles.css
Hovering on the count highlights the respective results.
> Count succeeded, unsupported and failed tests. 

- run.py
> fix crash when using the replace option

- .github/workflows/interop.yml
> fix docker pull command in interop GitHub Actions script

- .github/workflows/interop.yml
- .gitignore
- README.md
- certs.sh
- docker-compose.yml
- interop.py
> generate the certificate chain and mount it into the implementations

- testcases.py
> only test for key phase 1 packets in the key update test

- docker-compose.yml
- testcases.py
The difference being that in the latter, client IP addresses also change.
Depends on https://github.com/marten-seemann/quic-network-simulator/pull/83
> Add a NAT and CGN rebind test

- cert_config.txt
- certs.sh
Should have been part of #197.
> add forgotton openssl cert config file

- trace.py
> fix packet types in the trace analyzer

- testcases.py
- trace.py
> fail the amplification limit test if a VN packet is sent

- certs.sh
- docker-compose.yml
- interop.py
- testcases.py
- trace.py
Depend on https://github.com/marten-seemann/quic-network-simulator/pull/87
> Add an IPv6-only test case

- testcases.py
As Handshake packets might be padded as of draft-32, we can't use the payload size any more.
> check for the absence of the TLS Certificate message in resumption test

- README.md
> README: list latest Wireshark version as 3.4.2

- docker-compose.yml
- interop.py
- testcases.py
And pass the desired version into the endpoint script environment.
> Bump the version to 0x1

- testcases.py
https://github.com/marten-seemann/quic-interop-runner/runs/2008826329?check_suite_focus=true#step:15:30
> Try and fix the int conversion issue

- implementations.json
Add a new implementation to test haproxy QUIC interop. This
implementation fullfil the server role only.
> add haproxy implementation

- implementations.json
Hello Marten,
Thanks for the great tooling! 
Here is an addition for [Quinn](https://github.com/quinn-rs/quinn/) implementation.
> Add Quinn implementation

- implementations.json
> remove quicly

- README.md
Add a requirement section, including Docker and docker-compose.
Fix #292
> Update readme for requirements

- implementations.json
xquic interop image has moved to ghcr.io.
> update xquic image

- web/index.html
GitHub branch renaming. The gift that keeps on giving.
> fix link to QUIC logo

- implementations.json
> remove quant

- .github/workflows/interop.yml
Backblaze doesn't support displaying index.html files. This seems to be a conscious design decision on their end, which means we can't use them for our purposes. This reverts #319.
> ci: stop uploading to Backblaze

- web/index.html
- web/styles.css
I'm paying for the upkeep of the QUIC interop runner out of pocket, and I'm doing all the maintenance work in my free time. Sponsorships would be greatly appreciated.
> add a sponsor button to the website

- .github/workflows/interop.yml
Looks like #337 messed up the upload path for the log files. Thanks to @ptrd for noticing!
> fix upload path for log files

- interop.py
Introduced in #355. cc @mxinden
> fix incorrect client field in JSON output

- interop.py
- run.py
> feat: Add option to output table in Markdown format

- interop.py
If a client or a server fails a test against all servers or all clients, mark that test as unsupported, even if the implementation didn't explicitly do so.
Fixes #387
> feat: Auto-mark as unsupported

- testcases.py
Because otherwise they do nothing...
> Parameterize the burst rate error models

- .github/workflows/interop.yml
- testcases.py
Alternative to https://github.com/quic-interop/quic-interop-runner/pull/269
Thanks to @sedrubal for the groundwork
> Embed sslkeylog files into pcaps

- .github/workflows/interop.yml
Rather than building from source.
> ci: Use the new wireshark nightly PPA
