interop.py
This will make it easier to debug test failures when the file comparison fails.
=> save files in www and downloads when a test fails

docker-compose.yml, interop.py
Docker mounts are very slow on OSX when the container performs many writes. It's better to just use `docker cp` to copy over the pcaps after the test run has finished.
Requires https://github.com/marten-seemann/quic-network-simulator/pull/55.
=> use `docker cp` instead of a mount to retrieve the pcaps from the sim

docker-compose.yml
As of https://github.com/marten-seemann/quic-network-simulator/pull/56, we don't add the IP addresses to `/etc/hosts` in the setup script any more. Unfortunately, docker doesn't set up the routing automatically, so we have to add `/etc/hosts` entries in `docker-compose.yml`.
This is a better way than doing it in the setup script, since it is more flexible: The entry is set at container startup, not during the build of the container.
=> add the server's IP address to the client's /etc/hosts

README.md, testcases.py
The test is not working (see #20) and the failures are only creating confusion.
=> disable the version negotiation test

.gitignore, README.md, run.py, setup.py
I found that `pycyripto` is not listed in README's `pip3 install ...` instruction, so this PR fixes the problem with `setup.py`.
=> add setup.py to install deps easily

interop.py, testcases.py
We should probably edit the description of the `transfer` test case and add all the different tests we're using that one for.
=> add an interop test that blackholes packets for 2s

docker-compose.yml, interop.py
Depends on https://github.com/marten-seemann/quic-network-simulator/pull/62.
Unfortunately, we'll have to ask everyone to rebuild their endpoint image. Also, this doesn't resolve the osxfs problem with the download directory yet.
=> use docker cp to copy logs from the endpoints

testcases.py
Depends on #43.
This test case generates 2000 small (32 byte) files. It is expected (though not checked) that the server's stream limit is lower than 2000, so in order to complete this test, peers will open up to the maximum number of allowed streams, and will have to send MAX_STREAMS frames.
Again, we don't need to ask implementations to change anything. The `transfer` test already provides everything we need.
=> add a multiplexing test case

testcases.py, trace.py
Depends on #42.
Hopefully we can recover from the tshark crashes this way.
=> handle pyshark crash when reading invalid pcap files

README.md, testcases.py
Fixes #27.
Tests creation of 100 connections, at 30% loss in each direction, to ensure connection setup resiliency to high loss.
This test uses a new "multiconnect" testcase that requires a client to use a separate connection for each request.
=> Add high loss test for handshake

testcases.py
Not really happy with the name and the abbreviations...
At a packet loss rate of 2% and a MTU of 1500 bytes, we can expect 27 dropped packets. This should trigger early / fast retransmit loss recovery mechanisms.
=> add a test case that drops packets during a transfer

testcases.py
Fixes #55. Depends on #56.
It's easier to look at the SCID of Initial packets sent from the server. The server shouldn't send any Initial packets after receiving a NCID frame (which is sent in 1-RTT packets), so we won't get an inflated count that way.
Furthermore, unless the server does stupid things, it will use a non-zero CID.
=> fix handshake counting

trace.py
This helps debug situations such as `tshark` not being on the PATH. For
instance on Debian, `tshark` is packaged separately from `wireshark`.
=> Print exceptions raised by pyshark

interop.py
This should fix the issue that @ptrd encountered.
=> shut down containers when a test times out

.travis.yml, .travis/script, implementations.py, interop.py, pull.py, run.py, setup.cfg, testcases.py, trace.py
Add a script to make Travis enforce formatting and linting using 3 tools:
- black ensures consistent formatting
- isort ensures consistent ordering of imports
- flake8 is a linter and catches things like unused imports and variables or references to non-existant variables
=> Reformat code using `black`, sort imports using `isort`

trace.py
This should fix the problem that @huitema encountered. Maybe also fixes #71.
=> force Wireshark to decrypt UDP 443 as QUIC

docker-compose.yml
This should fix the crash I'm seeing with quic-go:
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
```
Updating the kernel is not possible without a big hassle, since Ubuntu 19.10 ships with 5.3.10.xx.
=> increase memlock ulimit for endpoint containers

testcases.py
Fixes #77.
Depends on https://github.com/marten-seemann/quic-network-simulator/pull/66.
=> add test cases that corrupt packets during the handshake and transfers

interop.py
check return code for docker-compose commands at the end of a run
for other subprocess invocations there are already checks on the output
and similar.
The cp commands at the end of the run were failing silently instead.
This solution throws an exception and makes it obvious that something
went wrong
```
$ python3 run.py -s quicgo -c mvfst -t resumption
Running with server quicgo (martenseemann/quic-go-interop:latest) and client mvfst (lnicco/mvfst-qns:latest)
quicgo client compliant.
quicgo server compliant.
mvfst client compliant.
mvfst server compliant.
Server: quicgo. Client: mvfst. Running test case: resumption
Traceback (most recent call last):
File "run.py", line 110, in <module>
output=get_args().json,
File "/home/ubuntu/lnicco/docker-interop/quic-interop-runner/interop.py", line …
```
=> check return code for docker-compose commands at the end of a run

.gitignore, cron.py, interop.py, run.py, web/index.html, web/script.js, web/styles.css
It's annoying that results disappear all the time. It's even more annoying that it's not predictable when this happens, and that the links to log files are just replaced by new files.
This PR:
* creates unique directory names for runs. For example, the link to a run will be https://interop.seemann.io/logs_20-04-11T16:21:04UTC/quicly_quicgo/handshake/. This link remains valid after another run of the interop runner. If at some point logs are deleted, it will 404.
* moves some of the logic of the previous cron job (which was not committed to CVS) to `cron.py`. This script runs the interop runner, and saves the log files. If there are more than `n` log file directories, it deletes the oldest one(s).
* adds a selector in the web interface to access all runs that we have log files available …
=> keep the log files of multiple runs, and show them in the web interface

README.md, docker-compose.yml, interop.py, testcases.py
I noticed that most implementations always negotiate AES. After discovering a few bugs in quic-go related to the ChaCha20 header protection, I thought it might be a good idea to have an interop test for this.
To support this test case, the client needs to support the `chacha20` test case. In this test case, it must only offer the ChaCha20 cipher suite during the handshake. This guarantees that if the transfer completes, ChaCha20 was actually used.
Servers don't need to change anything to support this test case.
=> add a ChaCha20 test case

testcases.py
@larseggert noticed that the error message for the ChaCha20 test was off. This PR fixes the ciphersuite check. It also increases the file size of the file transferred, in order to run ChaCha20 header protection more often than just 10 times or so.
=> ChaCha20 fixes

testcases.py
Operating right at the length limit of the file system is annoying, for example if you want to gzip the files...
=> slightly reduce the file name length in the 0-RTT test case

web/script.js
As chatted on slack.
Anchor element without href attribute is used to keep the same amount of word spacing.
Just creating text element is also possible, then we need some manual spacing.
=> Remove href from anchor for unsupported test case

interop.py, testcases.py
Fixes #116.
This PR adds additional verification logic for multiplexing test. **If** we have manage to decrypt the pcap (by using either the client's or the server's key log file), we can check the `initial_max_streams_bidi` transport parameter sent by the server. If this limit is not less than 1000, we fail the test.
If we don't have access to any key log file, we won't be able decrypt the trace, so we skip this verification step. This is not ideal, but I don't see any other solution (as long as we don't force implementations to expose the key log file).
=> verify the server's bidirectional stream limit in the multiplexing test

interop.py
This helps during development, when volumes might go missing.
`-V` [documentation](https://docs.docker.com/compose/reference/up/) says:
```
-V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
data from the previous containers.
```
In other words, it says that you should not try to revive a stopped image that you previously used, but go back to docker and load the image.  I think that this means "don't cache $something".  All I know is that it works.
Sorry about targeting the wrong repo.  I don't know what happened.
Closes #137.
=> Renew anonymous volumes

pull.py
cc @nibanks 
Example:
```bash
python3 pull.py -i quic-go,quicly,msquic
```
Note: The network simulator and the iperf endpoint are always pulled.
=> add a command line flag to pull.py to pull specific implementations

implementations.py
cc @nibanks
Running `python3 implementations.py` would now output:
```json
{
"server": ["quic-go", "quicly", "ngtcp2", "quant", "mvfst", "quiche", "picoquic", "aioquic", "neqo", "nginx", "msquic", "pquic"],
"client": ["quic-go", "quicly", "ngtcp2", "quant", "mvfst", "quiche", "kwik", "picoquic", "aioquic", "neqo", "pquic"]}
}
```
We can use that in the CI config to retrieve the list of implementations, so that we only have to hard-code them in a single place (`implementations.py`).
=> export the implemenations in JSON format

.github/workflows/interop.yml
This makes it easier to try out new things in the interop script, without uploading new results for every run.
Results are only uploaded if this run was triggered by the cron scheduler.
=> only upload interop results for scheduled runs

implementations.json
ngtcp2 interop image has moved to ghcr.io.
=> Update ngtcp2 image

.github/workflows/interop.yml, web/Caddyfile, web/script.js
I moved interop.seemann.io to a new (much weaker, CPU- and RAM-wise) server. This will allow us to spend more on hard drive space for logs, if necessary.
=> change paths of the log directory for the new interop.seemann.io setup

.github/workflows/interop.yml
This brings down the compilation time of Wireshark from 15 to 5 minutes. It also speeds up the installation of tshark on the test images (which took around ~45s), as we only have to install tshark, and not the Debian packages containing all Wireshark tools. Now installing tshark only takes ~5s.
Thanks to @Lekensteyn for helping me with the build configuration.
=> speed up the Wireshark build

web/script.js, web/styles.css
Sometimes it takes a second or so to load the result. This PR adds a visual loading indication.
Already deployed on interop.seemann.io.
=> fade the result tables while loading a new result

testcases.py
Fixes #150. Closes #151.
cc @larseggert
=> improve error message when the wrong number of files was downloaded

.github/workflows/interop.yml
Some people complained that the GitHub Actions run ID is not a very user-friendly identifier for a run.
We can just go back to using the current date again.
=> use the current date as a name for an interop run

.github/workflows/interop.yml
Turns out that GitHub actions doesn't evaluate the environment variables quite the way I expected, which resulted in logs being uploaded to the wrong directory.
=> fix passing of upload directory variable

docker-compose.yml
See https://docs.docker.com/compose/compose-file/#caching-options-for-volume-mounts-docker-desktop-for-mac
=> Make mounts delegated, which has some minor speed benefits on Mac

.travis/script
Apparently version 5 of isort changed the command line flags.
=> fix invocation of isort on CI

.github/workflows/interop.yml
Fixes #171.
This PR implements a simpler solution than I initially came up with in #171. We add a configuration variable, WIRESHARK_CACHEKEY. The tshark binary is saved under this cache key, and can be restored from the cache, saving us about 7 minutes of checkout and compile time.
Whenever we need to re-compile Wireshark (for example because Wireshark added support for a new QUIC draft, or fixed a bug), we increment WIRESHARK_CACHEKEY. The next the interop runner runs, it won't be able to restore from that new cache key, and build a new tshark binary from the current master of Wireshark, and save it under the new cache key.
=> cache the Wireshark build

README.md, interop.py, result.py, testcases.py
Fixes #95. 
This tests presents itself as "keyupdate" to the client and as "transfer" to the server.
The client is expected to make sure that a key update happens (although it is not *required* to initiate it, if the server initiates the key update, that's fine too). Test verification looks at the decrypted PCAP and checks that both client and server sent at least one packet in key phase 0 and one packet in key phase 1.
If no SSLKEYLOG is available (as is the case in the mvfst - mvfst tests), the test status is report as "unsupported". I also changed the multiplexing test to behave analogously.
=> add a key update test

trace.py
Some runs of the interop runner take insanely long, e.g. this picoquic - quiche run took more than 1.5 hours: https://github.com/marten-seemann/quic-interop-runner/runs/1095324523?check_suite_focus=true
It turns out that trace parsing is the culprit here. For some traces, parsing the last packet of a stream takes around 2 minutes on my machine. Here's a minimal example generated from a picoquic - quiche run: 
[Archive (3).zip](https://github.com/marten-seemann/quic-interop-runner/files/5201726/Archive.3.zip)
Disabling HTTP/3 support in tshark seems to solve this problem. As we're currently not parsing HTTP/3 frames at all, this is an easy workaround.
=> disable tshark HTTP/3 support as a workaround for slow trace processing

implementations.json
It's not easy to convince Chrome Headless to download files to disk: https://github.com/marten-seemann/chrome-quic-interop-runner.
The test will only succeed if implementations use the certificate chain provided by the interop runner (#194).
=> add Chrome (HTTP/3-only)

.github/workflows/interop.yml
Interop tests with Chrome won't run any measurements. Make sure the job doesn't error because of that.
=> fix measurement failure when no measurements were run

.github/workflows/aggregate.py, interop.py
They got dropped during aggregation.
Also, only include URLs for those implementations that were part of the run.
=> Fix inclusion of implementation URLs

.github/workflows/interop.yml, certs.sh, interop.py, testcases.py
The certificate chain will be generated in a temporary directory, so people won't have to run `certs.sh` manually any more.
=> generate a new certificate chain for every test

run.py
```
❯ python3 run.py -t invalid
Test case invalid not found.
Avaiable testcases: handshake, transfer, longrtt, chacha20, multiplexing, retry, resumption, zerortt, http3, blackhole, keyupdate, ecn, handshakeloss, transferloss, handshakecorruption, transfercorruption, rebind-port, rebind-addr
Available measurements: goodput, crosstraffic
```
=> improve error message for invalid test case names

.travis/script, certs.sh, testcases.py, trace.py
cc @larseggert 
Depends on #196.
I already heard that some implementations ignore the MUST in the spec and send 3.x * what the client sent (e.g. quicly). We might want to relax the test here a bit, if we want to accommodate those implementations. Or we might call them out for violating the spec.
=> add a test case for the amplification limit

.github/workflows/interop.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
=> use the new environment file syntax

certs.sh
Turns out that `seq 9 1` on OSX gives you the numbers from 9 to 1 (in descending order), whereas the same command returns and empty output on Linux.
=> fix generating of long certificate chains on Linux

README.md, testcases.py
CAUTION: This is a breaking change. Server implementations will (probably) have to be updated
mvfst doesn't support ChaCha20 header protection, and therefore this test always fails.
cc @martinthomson @mjoras
=> use chacha20 as test name for the ChaCha20 test for the server

testcases.py
=> use the UDP payload size when counting bytes in the amplification test

testcases.py
Many implementations implement a 3.x amplification limit instead of a 3x amplification limit. This seems a reasonable thing to do, as it achieves a limit of the amplification factor, and 3 is an arbitrary value anyway.
I'm aware that this PR will make the people who argue that the interop runner should test _exactly_ what the spec says unhappy. There's no way to satisfy both.
=> allow up to 3.x amplification in the amplification limit test

implementations.json
xquic is Alibaba's QUIC implementation,  are planning to join the interop project.
xquic is able to interop with most implementations, version negotiation/handshake/longrtt are suported now, and more testcases are in progress.
Cause xquic is planned to be openned source around the end of this year, so far I am only able to use the binary files other than the source code of xquic. the image and url infomation of xquic might be changed if xquic is made open.
=> add xquic interop docker image

testcases.py
This avoids trying to use keylogs that still contain entries with the old `QUIC_` prefix.
=> Make sure the keylog exists and sanity-check the contents

.github/workflows/interop.yml, trace.py
And log the details of undecryptable packets to the debug log only.
=> Now that wireshark has fewer bugs, don't blame it.

testcases.py
Otherwise keylogs that use a comment or something else in the first line are erroneously rejected as invalid.
=> Don't just check the first line for a match

interop.py
This is so that log files are still preseved for examination
=> Catch FileNotFound exception in testcase.check()

web/index.html, web/script.js, web/styles.css
This aligns the text like this:
And it also fixes the hover effect for the last column 😉
=> Enhance website

implementations.json
Point to the new location for MsQuic, on the GitHub registry. Also uses the tag `main` instead of `latest`. cc @anrossi @thhous-msft
=> Update MsQuic to GitHub Registry

testcases.py
`0x1303` equals to `4867`. However, some platforms such as nginx-quic who returned `0x1303` instead are treated as failure:
> python3 run.py -s nginx -c neqo -t chacha20
then get:
> Expected only ChaCha20 cipher suite to be offered. Got: {'0x1303'}
Fix now.
=> Fix ChaCha20 test failed when returned 0x1303

testcases.py
If <ciphersuites> set may be filled with hexadecimal strings, as deduced from
86f5d35e7 previous committhis test can pass only if these two assertions are true:
len(set(ciphersuites)) == 1
ciphersuites[0] == "4867" or ciphersuites[0] == "0x1303"
So 86f5d35e7 previous commit is not correct (logic issue).
=> Wrong logic in previous fix for chacha20 test

implementations.json
xquic is officially opened: https://github.com/alibaba/xquic
=> update the url of xquic

implementations.json
This change adds [s2n-quic](https://github.com/aws/s2n-quic) to the list of implementations
=> add s2n-quic implementation

.github/workflows/interop.yml, README.md, testcases.py, trace.py
This PR adds a test case which asserts that client and server negotiate QUIC v2 draft version using compatible version negotiation.
When wireshark gets support of latest version_information transport parameter, it would be nice to add a check for chosen_version field.
wireshark cache key is updated to bring wireshark which supports QUIC v2 draft.
=> Add v2 testcase

trace.py
When `cap.set_debug()` is set on the pyshark capture object, tshark prints the warning:
> ** (tshark:810515) 11:02:35.574079 [Epan WARNING] epan/prefs.c:5570 -- set_pref(): Preference "ssl.keylog_file" has been converted to "tls.keylog_file"
This MR fixes it.
=> Fix `Preference "ssl.keylog_file" has been converted to "tls.keylog_file"`

testcases.py, trace.py
We are no longer able to add sniff_time to XmlLayer object due to the
recent refactoring on pyshark.  In order to workaround this, add new
function get_1rtt_sniff_times to TraceAnalyzer which returns 1RTT
packets as well as first and last sniff times.
=> Add a function to return first and last sniff times

.github/workflows/interop.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
=> stop using the deprecated set-output commands

.github/workflows/interop.yml
Ubuntu libpcap now depends on dbus which in turn depends on
libsystemd.  Wireshark build system cannot deal with this dependencies
when statically linking libpcap.  To workaround this issue, build our
own libpcap without dbus support.
=> Fix wireshark build

testcases.py
Wireshark now does not add "tls_handshake_type" attribute to a retransmitted Initial packets which contain CRYPTO frame.  Instead, it adds either "retransmission" or "overlap" attribute.  Consider these attributes as a sign of retransmission of ClientHello.
See https://gitlab.com/wireshark/wireshark/-/issues/18696 for details.
=> Fix longrtt

docker-compose.yml
When experimenting with non-root `podman` (a replacement for `docker`), the network-simulator container named `sim` when launched, runs into exception and the tests fail with:
```
Creating sim ... 
Creating sim ... done
Creating client ... 
Creating client ... done
Attaching to sim, client
sim             | Using scenario: simple-p2p --delay=15ms --bandwidth=10Mbps --queue=25
sim             | ../src/fd-net-device/helper/raw-sock-creator.cc: fatal error at line 86: main(): CreateSocket(): Unable to open raw socket
sim             |     errno = 1 (Operation not permitted)
sim             | msg="EmuFdNetDeviceHelper::CreateFileDescriptor(): socket creator exited normally with status 255", +0.000000000s -1 file=../src/fd-net-device/helper/emu-fd-net-device-helper.cc, line=335
sim …
```
=> Add NET_RAW capability to the quic-network-simulator container

certs.sh
=> Use a more portable shebang

.github/workflows/interop.yml
In preparation for a switch of the storage backend. With this PR, we're uploading the logs to Backblaze _in addition_. This serves to validate that everything works as intended first. The upload to `interop.seemann.io` will be removed in a future PR.
=> upload results to Backblaze

interop.py
When running all interop tests (without specific test selection)
```console
python run.py -c ... -s ...
```
the interop runner logs messages when a test completes. The log looks something like:
```console
Test: transfercorruption took 31.123s
```
Given that the entire run can take a long time to complete, I have found that including the test's status in the log message to be useful. That way I don't have to wait for entire run or try to search for other log messages to understand which tests failed and which ones passed so far.
The change in this PR proposes to include the test's status in this above log message when a test completes. So the log would now look like:
```console
Test: transfercorruption took 31.123s, status: TestResult.SUCCEEDED
```
Does this look like a change that can be …
=> Include the test status in the log message when a test completes

README.md
With #333, we should now (finally!!) support docker compose v2.
=> README: update docker compose requirements

web/Caddyfile
HTTP/3 is not experimental anymore.
=> remove experimental_http3 flag from Caddyfile

testcases.py
Hello Marten @marten-seemann, I was running the key update test today and I noticed that it no longer works and the test always fails on my setup. It looks like the issue is just related to the parsing of the captured packets and appears to have been caused by the changes in https://github.com/quic-interop/quic-interop-runner/pull/332.
The commit in this PR introduces a way to retain that newly introduced change as well as retain the older way, by allowing both the values "1" and "True" to be considered as key phase 1. With this change, the test now passes for me locally.
Perhaps @tatsuhiro-t too might want to give this change a try?
=> fix key_phase bit check in captured packets

implementations.json
Updates the s2n-quic-qns image host to DockerHub.
=> Pull s2n-quic from DockerHub

implementations.json
Neqo's interop runner Docker image is now hosted on GitHub's container registry and continuously updated via a daily GitHub action.
See https://github.com/mozilla/neqo/issues/1552 for details.
//CC @martinthomson and @larseggert
=> fix(implementations): update neqo image to new repository

implementations.json
NGINX QUIC interop image has moved to GitHub Registry, addressing issues related to AWS ECR rate limits encountered previously (referencing issue #345). cc @thresheek
=> Update NGINX to GitHub Registry

testcases.py
Apparently Python developers think it's okay to break other people's (CI) build by just changing the way the code formatter works. Combined with a lack of version pinning this leads to unexpected CI failures like https://github.com/quic-interop/quic-interop-runner/actions/runs/7698591583/job/20978213685.
=> reformat code using black

.github/workflows/interop.yml
Some implementations have delayed the interop runner by hours recently (see #350). Most implementations take ~15 minutes to complete the full suite of tests, so a 45 minute timeout is really generous.
Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> ci: enforce a 45 minute timeout per test run

interop.py, result.py
Previously the test abbreviation was printed in green, grey and red depending on the result. Colors are not available in all environments, e.g. when printing into a file.
This commit adds symbols in addition to colors.
```
+------+--------+
|      |  neqo  |
+------+--------+
| neqo | ✓(H,S) |
|      |  ?()   |
|      |  ✕(R)  |
+------+--------+
```
Any format works for me. Using parenthesis first came to mind.
=> feat: print result symbol in addition to color

.github/workflows/cleanup.yml, .github/workflows/interop.yml
We need to clean up old log files on interop.seemann.io, otherwise we'll run out of hard disk space. This is what has been happening the last couple of weeks, and is the reason the interop runner was stopped.
Previously, this cleanup was done by a cron job on interop.seemann.io, but it was lost when I migrated the server to a different cloud provider. By moving the cleanup logic into a GitHub Action in this repository, we reduce the complexity required on the server side, which should make it easier to migrate it again in the future.
=> ci: clean up old runs on the server

interop.py, run.py
Introduce new command line flag `--must-include`.
When running the QUIC Interop Runner in CI of a single implementation, one is only interested in test pairs including that particular implementation. As an example, take a world with 3 QUIC implementations, quic-go, ngtcp2 and neqo. On the neqo CI one is not interested in the client-server pair quic-go->ngtcp2.
With this commit one can specify `--must-include neqo` on neqo's CI.
```
$ python3 run.py --test handshake --must-include neqo
Saving logs to logs_2024-02-24T17:39:08.
Server: neqo. Client: quic-go. Running test case: handshake
Server: neqo. Client: ngtcp2. Running test case: handshake
Server: quic-go. Client: neqo. Running test case: handshake
Server: ngtcp2. Client: neqo. Running test case: handshake
Server: neqo. Client: neqo. …
```
=> feat: add --must-include flag

.github/workflows/interop.yml
The latest version of the workflows (updated by Dependabot recently, cc @larseggert) fails if the artifact already exists. We could set the flag to overwrite existing artifacts, but the cleaner solution is to use a unique file name.
=> use unique names for quic-interop-iperf-endpoint and quic-network-simulator artifacts

web/index.html, web/script.js
Hello Marten @marten-seemann, I don't know if this change is of interest, but I thought I will raise this PR. I found it hard to link to specific runs in our internal tests, so I decided to implement this and I find this to be useful.
The web page which displays the interop test results (like here https://interop.seemann.io/) has a drop down of test runs. The first selection in it is the latest run. 
Sometimes, it's useful to directly link to a specific run so that the selected run is what gets displayed. It's currently not possible to have a direct link to a specific run.
The commit in this PR proposes to introduce an optional `run` query param which can be used to specify the test run that has to be displayed. It can then be directly linked as `https://interop.seemann.io/?run=456`, …
=> allow to explicitly pass a "run" query param to the results page

certs.sh
This is part of what's needed to make the Interop Runner work for WebTransport, since `serverCertificateHashes` only works with non-RSA certificates that are valid for less than 14 days.
cc @Yanmei-Liu
=> switch certificates to ECDSA, limit validity to 10 days

interop.py
Previously when calculating each cell of the _measurements_ result table, instead of always setting a cell, a cell would be appended in case one already existed. Appending a cell to another doesn't make sense in this context. In addition this code also errors, given that on the first cell `row[server] +=` results in a `KeyError`.
```
Traceback (most recent call last):
File "run.py", line 168, in <module>
sys.exit(main())
File "run.py", line 150, in main
return InteropRunner(
File "/home/runner/work/quic-go/quic-go/quic-interop-runner/interop.py", line 529, in run
self._print_results()
File "/home/runner/work/quic-go/quic-go/quic-interop-runner/interop.py", line 243, in _print_results
row[server] += "\n".join(results)
KeyError: 'quic-go-latest'
```
See e.g. …
=> fix(interop.py): override instead of append to row[server]

implementations.json
This switches the mvfst interop image to one that is published using a Github workflow:
https://github.com/facebook/proxygen/blob/v2024.03.25.00/.github/workflows/publish_mvfst_interop.yml
This image is updated weekly.
=> Update mvfst interop image

implementations.json
This change updates the [s2n-quic image](https://github.com/aws/s2n-quic/pkgs/container/s2n-quic%2Fs2n-quic-qns) to pull from GitHub Container Repository instead of Docker Hub
=> updating s2n-quic image to GitHub Container Repository

interop.py
Previously, when printing the measurements result table, one would initialize the `t.field_names` field to `[""]`. Later on `t.field_names` would be overwritten by the actual table column names, namely the servers under test.
Each time one sets `t.field_names`, the `field_names` setter logic would run.
https://github.com/jazzband/prettytable/blob/1f156f8f82a8442fcec332018de0d66fa308acce/src/prettytable/prettytable.py#L605-L608
Among this is `validate_field_names`, which asserts that the number of fields from the second assignment equals the number of fields of the first assignment.
https://github.com/jazzband/prettytable/blob/1f156f8f82a8442fcec332018de0d66fa308acce/src/prettytable/prettytable.py#L411-L421
Initializing `t.field_names` with `[""]` is not neccessary. Thus, to prevent the …
=> fix(interop/measurements): don't initialize t.field_names

interop.py
Previously when providing `--markdown` flag, only the tests table would be formatted in Markdown format.
With this patch, both the tests and the measurements table are formatted using markdown.
---
Follow-up to https://github.com/quic-interop/quic-interop-runner/pull/372/.
=> feat: optional measurements markdown table

interop.py, run.py
* Add a `--no_auto_unsupported` argument to exclude implementations from auto-marking (e.g., when QNS is run as part of CI for an implementation)
* If there is only a single server or client implementation given, also don't automatically mark as unsupported
* Add some log messages when auto-marking to explain what is going on
=> fix: Fixes related to "auto-unsupported"

interop.py
This should fix the issue noted in https://github.com/quic-interop/quic-interop-runner/issues/390. 
The root cause of this issue that the in the change here https://github.com/quic-interop/quic-interop-runner/pull/355, we introduced the use of a `set()` for clients and servers https://github.com/quic-interop/quic-interop-runner/pull/355/files#diff-a1f0ac428938a846f118f59aa8e2e66b90bff7b498b928204eb3bfcb41f1f528R245, which cause the clients/servers to be potentially in a different order than the iteration order that we use later a few lines below https://github.com/quic-interop/quic-interop-runner/pull/355/files#diff-a1f0ac428938a846f118f59aa8e2e66b90bff7b498b928204eb3bfcb41f1f528R267.
The commit in this PR, addresses that by changing the iteration logic to iterate in the same order as …
=> Maintain the right order of client/server while exporting the results to JSON

certs.sh
The old code would not work on macOS, giving errors like `tls: failed to parse certificate from server: x509: SAN dNSName is malformed`.
=> fix: Make sure `fakedns` is alphanumeric

testcases.py
Because I think the algorithm in RFC9000 says "probe with N marked packets, then check the ACKs", which implies that an implementation needs to stop marking after N to have a stable comparison value.
=> fix: Allow non-ECN marks when validating

testcases.py
The move operation can fail in certain conditions. Copy is more robust.
=> fix: Copy pcap files

interop.py
It doesn't make sense to automatically claim a test as unsupported if we're only testing a single implementation.
=> fix: Disable auto-unsupported for single server/client tests

testcases.py
Inherit from `TestCasePortRebinding` rather than `TestCaseAddressRebinding`.
Fixes #419
=> fix: Don't require multiple addresses for CM testcases

trace.py
Non-QUIC packet can slip through in certain cases.
This change is to log the message instead of crashing whole test.
=> ignore non-QUIC packets in trace analysis (#421)
